# Use postgres/example user/password credentials
version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://pweb:pweb@db:5432/fast_api
    depends_on:
      - db
  db:
    image: postgres

#    restart: always
#     set shared memory limit when using docker-compose
#    shm_size: 128mb
#     or set shared memory limit when deploy via swarm stack
#    volumes:
#      - type: tmpfs
#        target: /dev/shm
#        tmpfs:
#          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: pweb
      POSTGRES_PASSWORD: pweb
      POSTGRES_DB: fast_api

    ports:
      - "5432:5432"
