version: '3.9'

services:
  bet_maker:
    build:
      context: .
      dockerfile: Dockerfile_bm
    ports:
      - "8000:8000"
    volumes:
      - .:/bet_maker
    environment:
      - DATABASE_URL=postgresql://pweb:pweb@db1:5432/fast_api_bm
    depends_on:
      - db1
    networks:
      - app_network

  line_provider:
    build:
      context: .
      dockerfile: Dockerfile_lp
    ports:
      - "8001:8001"
    volumes:
      - .:/line_provider
    environment:
      - DATABASE_URL=postgresql://pweb:pweb@db2:5432/fast_api_lp
    depends_on:
      - db2
    networks:
      - app_network
  db1:
    image: postgres
    container_name: db1
    environment:
      POSTGRES_USER: pweb
      POSTGRES_PASSWORD: pweb
      POSTGRES_DB: fast_api_bm
    ports:
      - "5434:5432"
    networks:
      - app_network

  db2:
    image: postgres
    container_name: db2
    environment:
      POSTGRES_USER: pweb
      POSTGRES_PASSWORD: pweb
      POSTGRES_DB: fast_api_lp
    ports:
      - "5433:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
