FROM python:3.10-slim

WORKDIR /bet_maker

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "bet_maker.main:app", "--host", "0.0.0.0", "--port", "8000"]
